# Generated by Django 5.2.8 on 2025-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0002_alter_gene_gene_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
